// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import (
	api "bidder/code/database/api"
	id "bidder/code/id"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DeviceRepository is an autogenerated mock type for the DeviceRepository type
type DeviceRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0, _a1, _a2
func (_m *DeviceRepository) Get(_a0 time.Time, _a1 id.ID, _a2 *api.Device) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time, id.ID, *api.Device) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
