package ksuid

import (
	"math"
	"testing"

	"github.com/segmentio/ksuid"
	"github.com/stretchr/testify/assert"
)

// Test if more than math.MaxUint16 ksuids can be generated.
// math.MaxUint16 is the maximum number of ksuids that can
// be generated by underlying ksuid.Sequence.
func TestKsuidSequence(t *testing.T) {
	seq := NewSequence()
	for i := 0; i < math.MaxUint16+100; i++ {
		assert.NotEqual(t, ksuid.Nil, seq.Get())
	}
}
