apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: $CONTENT_NAME
  labels:
    app: $APP_NAME
spec:
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: $SNAPSHOT_NAME
    namespace: default
  source:
    snapshotHandle: $SNAPSHOT_ID
  driver: ebs.csi.aws.com
  deletionPolicy: Retain
  volumeSnapshotClassName: csi-aws-vsc
