// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	auction "bidder/code/auction"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Auction is an autogenerated mock type for the Auction type
type Auction struct {
	mock.Mock
}

// Run provides a mock function with given fields: _a0, _a1
func (_m *Auction) Run(_a0 time.Time, _a1 *auction.Request) (*auction.Response, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *auction.Response
	if rf, ok := ret.Get(0).(func(time.Time, *auction.Request) *auction.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auction.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(time.Time, *auction.Request) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
