---
replicaCount: 32
nodeSelector:
  pool: application
resources:
  limits:
    cpu: "1950m"
image:
  tag: AB-348-1-v3
config:
  DB_ACCESS_DISABLE: "false"
  DYNAMODB_DEVICE_TABLE: device_audience1

service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:${AWS_ACCOUNT}:certificate/bcf35a69-82a7-4b0b-b86c-243cbe6a7266"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
