package bid

// BidRequest3 fixture based on https://github.com/InteractiveAdvertisingBureau/openrtb for OpenRTB 3.0
const BidRequest3 = `{
  "openrtb": {
    "ver": "3.0",
    "domainspec": "adcom",
    "domainver": "1.0",
    "request": {
      "id": "0123456789ABCDEF",
      "tmax": 150,
      "at": 2,
      "cur": [
        "USD",
        "EUR"
      ],
      "source": {
        "tid": "FEDCBA9876543210",
        "ts": 1541796182157,
        "ds": "AE23865DF890100BECCD76579DD4769DBBA9812CEE8ED90BF",
        "dsmap": "...",
        "cert": "ads-cert.1.txt",
        "pchain": "..."
      },
      "item": [
        {
          "id": "1",
          "qty": 1,
          "deal": [
            {
              "id": "1234",
              "flr": 1.5
            }
          ],
          "spec": {
            "placement": {
              "dummy": "dummy"
            }
          }
        }
      ],
      "context": {
        "site": {
          "dummy": "dummy"
        },
        "user": {
          "dummy": "dummy"
        },
        "device": {
          "ifa": "9c1ce5bd-3013-5c90-2598-cd744e1c96d6"
        },
        "regs": {
          "dummy": "dummy"
        },
        "restrictions": {
          "dummy": "dummy"
        }
      }
    }
  }
}`

// BidRequest2 fixture based on BidRequest3 but for OpenRTB 2.5
const BidRequest2 = `{
  "id": "0123456789ABCDEF",
  "tmax": 150,
  "at": 2,
  "cur": [
    "USD",
    "EUR"
  ],
  "source": {
    "tid": "FEDCBA9876543210",
    "pchain": "...",
    "ext": {
      "ts": 1541796182157,
      "ds": "AE23865DF890100BECCD76579DD4769DBBA9812CEE8ED90BF",
      "dsmap": "...",
      "cert": "ads-cert.1.txt"
    }
  },
  "imp": [
    {
      "id": "1",
      "banner": {
        "ext": {
          "qty": 1
        }
      },
      "pmp": {
        "deal": [
          {
            "id": "1234",
            "bidfloor": 1.5
          }
        ]
      }
    }
  ],
  "site": {
    "name": "dummy"
  },
  "user": {
    "id": "dummy"
  },
  "device": {
    "ifa": "9c1ce5bd-3013-5c90-2598-cd744e1c96d6"
  },
  "restrictions": {
    "bcat": [
      "dummy"
    ]
  }
}`

// BenchmarkBidRequest3 fixture based on load-generator bid requests.
//nolint:lll // don't lint an autogenerated fixture
const BenchmarkBidRequest3 = `{
    "openrtb": {
        "ver": "3.0",
        "domainspec": "adcom",
        "domainver": "1.0",
        "request": {
            "id": "1nQSb41SvuYMALOiS1pslOvlHGf",
            "tmax": 51,
            "at": 1,
            "cur": [
                "USD"
            ],
            "source": {
                "tid": "1lmo0hJYZX5eH3BPmqHSVzYfSGa",
                "ts": 1611320889,
                "pchain": "1lmo0cdhb6woJTWl0Bouj5dXR5b"
            },
            "item": [
                {
                    "id": "1nQSb4hpjPgxAINsLWdBhJZmkUu",
                    "qty": 2,
                    "flr": 3.58,
                    "flrcur": "USD",
                    "exp": 4,
                    "spec": {
                        "placement": {
                            "tagid": "1nQSb6LpN743FfEwedJnWrv0zen",
                            "ssai": 1,
                            "display": {
                                "mime": "text/html",
                                "w": 1767,
                                "h": 1092,
                                "unit": 1
                            }
                        }
                    }
                }
            ],
            "context": {
                "site": {
                    "domain": "example.com",
                    "page": "http://easy.example.com/easy?cu=13824;cre=mu;target=_blank",
                    "ref": "http://tpc.googlesyndication.com/pagead/js/loader12.html?http://sdk.streamrail.com/vpaid/js/668/sam.js",
                    "cat": [
                        "1",
                        "33",
                        "544",
                        "765",
                        "1222",
                        "1124",
                        "789",
                        "995",
                        "133",
                        "45",
                        "76",
                        "91"
                    ],
                    "pub": {
                        "id": "qqwer1234xgfd",
                        "name": "site_name",
                        "domain": "my.site.com"
                    }
                },
                "user": {
                    "id": "1nQSb4rMriy3eo43fZIrR74qGjs",
                    "buyeruid": "1nQSb9fP14KbRLJiOv7K01Fg6rx",
                    "yob": 1961,
                    "gender": "F",
                    "data": [
                        {
                            "id": "pub-demographics",
                            "name": "data_name",
                            "segment": [
                                {
                                    "id": "345qw245wfrtgwertrt56765wert",
                                    "name": "segment_name",
                                    "value": "segment_value"
                                }
                            ]
                        }
                    ]
                },
                "device": {
                    "type": 2,
                    "ifa": "a64140cbff371cdcd47d70e103995b46",
                    "os": 2,
                    "lang": "en",
                    "osv": "10",
                    "model": "browser",
                    "make": "desktop",
                    "ip": "104.4.9.67",
                    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "geo": {
                        "lat": 37.789,
                        "lon": -122.394,
                        "country": "USA",
                        "city": "San Francisco",
                        "region": "CA",
                        "zip": "94105",
                        "type": 2,
                        "ext": {
                            "dma": 650,
                            "state": "oklahoma",
                            "continent": "north america"
                        }
                    }
                },
                "restrictions": {
                    "cattax": 2,
                    "bcat": [
                        "12",
                        "143",
                        "34",
                        "887",
                        "122",
                        "999",
                        "1023",
                        "13",
                        "4",
                        "565",
                        "920",
                        "224",
                        "857",
                        "1320"
                    ],
                    "badv": [
                        "facebook.com",
                        "twitter.com",
                        "google.com",
                        "amazon.com",
                        "youtube.com"
                    ]
                },
                "regs": {
                    "coppa": 0,
                    "gdpr": 0,
                    "ext": {
                        "sb568": 0
                    }
                }
            }
        }
    }
}`

// NoBidBidRequest3 fixture used to provoke no bid response by providing unknown device ID.
const NoBidBidRequest3 = `{
  "openrtb": {
    "request": {
      "id": "123",
      "item": [
        {
          "id": "1"
        }
      ],
      "context": {
        "device": {
          "ifa": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        }
      }
    }
  }
}`

// BenchmarkBidRequest2 fixture based on BenchmarkBidRequest3 but in a 2.x version.
//nolint:lll // don't lint an autogenerated fixture
const BenchmarkBidRequest2 = `{
  "at": 1,
  "badv": [
    "facebook.com",
    "twitter.com",
    "google.com",
    "amazon.com",
    "youtube.com"
  ],
  "bcat": [
    "12",
    "143",
    "34",
    "887",
    "122",
    "999",
    "1023",
    "13",
    "4",
    "565",
    "920",
    "224",
    "857",
    "1320"
  ],
  "cur": [
    "USD"
  ],
  "device": {
    "devicetype": 2,
    "ifa": "a64140cbff371cdcd47d70e103995b46",
    "ip": "104.4.9.67",
    "language": "en",
    "make": "desktop",
    "model": "browser",
    "os": "iOS",
    "osv": "10",
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
  },
  "ext": {
    "cattax": 2
  },
  "id": "1nQSb41SvuYMALOiS1pslOvlHGf",
  "imp": [
    {
      "banner": {
        "ext": {
          "qty": 2,
          "unit": 1
        },
        "h": 1092,
        "mimes": "text/html",
        "w": 1767
      },
      "bidfloor": 3.58,
      "bidfloorcur": "USD",
      "exp": 4,
      "ext": {
        "ssai": 1
      },
      "id": "1nQSb4hpjPgxAINsLWdBhJZmkUu",
      "tagid": "1nQSb6LpN743FfEwedJnWrv0zen"
    }
  ],
  "regs": {
    "coppa": 0,
    "ext": {
      "gdpr": 0,
      "sb568": 0
    }
  },
  "site": {
    "cat": [
      "1",
      "33",
      "544",
      "765",
      "1222",
      "1124",
      "789",
      "995",
      "133",
      "45",
      "76",
      "91"
    ],
    "domain": "example.com",
    "page": "http://easy.example.com/easy?cu=13824;cre=mu;target=_blank",
    "publisher": {
      "domain": "my.site.com",
      "id": "qqwer1234xgfd",
      "name": "site_name"
    },
    "ref": "http://tpc.googlesyndication.com/pagead/js/loader12.html?http://sdk.streamrail.com/vpaid/js/668/sam.js"
  },
  "source": {
    "ext": {
      "ts": 1611320889
    },
    "pchain": "1lmo0cdhb6woJTWl0Bouj5dXR5b",
    "tid": "1lmo0hJYZX5eH3BPmqHSVzYfSGa"
  },
  "tmax": 51,
  "user": {
    "buyeruid": "1nQSb9fP14KbRLJiOv7K01Fg6rx",
    "data": [
      {
        "id": "pub-demographics",
        "name": "data_name",
        "segment": [
          {
            "id": "345qw245wfrtgwertrt56765wert",
            "name": "segment_name",
            "value": "segment_value"
          }
        ]
      }
    ],
    "gender": "F",
    "geo": {
      "city": "San Francisco",
      "country": "USA",
      "ext": {
        "continent": "north america",
        "dma": 650,
        "state": "oklahoma"
      },
      "lat": 37.789,
      "lon": -122.394,
      "region": "CA",
      "type": 2,
      "zip": "94105"
    },
    "id": "1nQSb4rMriy3eo43fZIrR74qGjs",
    "yob": 1961
  }
}`
