version: "3.4"

services:
  aerospike:
    image: ${REGISTRY}/aerospike:5.5.0.3
    ports:
      - 3000-3003:3000-3003
    networks:
      - localstack
    healthcheck:
      test: ["CMD", "asinfo", "-v", "status"]

  bidder:
    depends_on:
      - aerospike

  datagen:
    depends_on:
      - aerospike
