apiVersion: batch/v1
kind: Job
metadata:
  name: load-generator
spec:
  ttlSecondsAfterFinished: 10
  parallelism: 1
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      nodeSelector:
        pool: benchmark
      serviceAccountName: load-generator-sa
      restartPolicy: Never
      containers:
        - image: ${AWS_ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/load-generator:latest
          name: load-generator
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 60
          env:
            - name: AWS_REGION
              value: us-east-1
          args:
            - --target=https://us-east-1.ab.clearcode.cc/bidrequest
            - --duration=3m
            - --rate=300000
            - --workers=60
            - --max-workers=1920
            - --profiler-url=http://bidder-internal:8091/debug/pprof/profile
            - --profiler-bucket=aws-bidder-benchmark-files
            - --profiler-output=
      securityContext:
        fsGroup: 3000 # to be able to read Kubernetes and AWS token files
