# Configuration for benchmark according to ADR
# extends values.yaml

nodeSelector:
  pool: aerospike

aerospikeNamespaceMemoryGB: 750
aerospikeReplicationFactor: 3

persistenceStorage:
  - name: data
    enabled: true
    mountPath: /data
    size: 750Gi
    volumeMode: Filesystem
    accessMode: ReadWriteOnce
    storageClass: csi-aws-ebs
