apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bidder.fullname" . }}-config
  labels:
    {{- include "bidder.labels" . | nindent 4 }}
data:
  {{- include "bidder.gomaxprocs" . | nindent 2 -}}
  {{- if not .Values.config.AWS_REGION }}
  AWS_REGION: {{ .Values.awsRegion }}
  {{- end }}
  {{- if not .Values.config.DAX_ENDPOINT }}
  DAX_ENDPOINT: "dax.{{ .Values.stackName }}.{{ .Values.awsRegion }}.ab.clearcode.cc:8111"
  {{- end }}
  {{- if not .Values.config.KINESIS_STREAM_NAME }}
  KINESIS_STREAM_NAME: "{{ .Values.stackName }}-bids{{ if .Values.useBenchmarkKinesis }}-benchmark{{ end }}"
  {{- end }}
  {{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
