apiVersion: v1
kind: Service
metadata:
  name: {{ include "bidder.fullname" . }}-internal
  labels:
    {{- include "bidder.internalLabels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceInternal.type }}
  ports:
    - port: {{ .Values.serviceInternal.port }}
      targetPort: {{ .Values.serviceInternal.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "bidder.selectorLabels" . | nindent 4 }}
