---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: {{ include "report-aggregator.fullname" . }}

rules:
  - apiGroups:
      - "*"
    resources:
      - pods
      - pods/log
      - jobs
    verbs:
      - get
      - list
