---
AWSTemplateFormatVersion: '2010-09-09'
Description: Guidance for Building a Real Time Bidder for Advertising on AWS (SO9111). Deploys Cloud9 Environment

Parameters:
  RootStackName:
    Type: String
    Description: Root Stack Name
  
  Subnet04:
    Type: String
    Description: Subnet to deploy the instance

Resources:
  AWSCloud9SSMAccessRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: RTB-AWSCloud9SSMAccessRole
        Description: Service role for Cloud9 access
        Path: /service-role/
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSCloud9SSMInstanceProfile
        AssumeRolePolicyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": [
                    "ec2.amazonaws.com",
                    "cloud9.amazonaws.com"
                  ]
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }
  AWSCloud9SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: AWSCloud9SSMInstanceProfile
      Path: /cloud9/
      Roles:
        - !Ref AWSCloud9SSMAccessRole

  C9Instance:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties: 
      AutomaticStopTimeMinutes: 30
      ConnectionType: CONNECT_SSH
      Description: !Sub '${AWS::StackName}-cloud9 instance'
      ImageId: amazonlinux-2-x86_64
      InstanceType: t3.xlarge
      # Fix for cloud9 client error
      Name: !Join
        - ''
        - - !Ref RootStackName
          - '-cloud9Instance' 
      Repositories: 
        - RepositoryUrl: https://github.com/owner/aws-rtbkit
          PathComponent: /RTBCodeKitRepo
      SubnetId: !Ref Subnet04 # TODO pull the subnet info using function

Outputs:
  Cloud9IDEURL:
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/cloud9/ide/${C9Instance}?region=${AWS::Region}=

  Cloud9EnvID:
    Description: cloud9 instance enevironment ID
    Value: !Ref C9Instance
    
