apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "model.fullname" . }}-config
  labels:
    {{- include "model.labels" . | nindent 4 }}
data:
  {{- include "model.gomaxprocs" . | nindent 2 -}}
  {{- if not .Values.config.AWS_REGION }}
  AWS_REGION: {{ .Values.awsRegion }}
  {{- end }}
  {{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
