apiVersion: v1
kind: Service
metadata:
  name: {{ include "model.fullname" . }}-internal
  labels:
    {{- include "model.internalLabels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceInternal.type }}
  ports:
    - port: {{ .Values.serviceInternal.port }}
      targetPort: {{ .Values.serviceInternal.targetPort }}
      protocol: TCP
      name: grpc
    - port: {{ .Values.serviceInternalHttp.port }}
      targetPort: {{ .Values.serviceInternalHttp.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "model.selectorLabels" . | nindent 4 }}
