{{- range $i, $e := until (.Values.service.count | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "model.fullname" $ }}{{ include "model.serviceSuffix" . }}
  labels:
    {{- include "model.labels" $ | nindent 4 }}
  {{- with $.Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{ if not (index $.Values.service.annotations "external-dns.alpha.kubernetes.io/hostname") -}}
    {{- if eq $.Values.stackName "model" -}}
    external-dns.alpha.kubernetes.io/hostname: {{ $.Values.awsRegion }}.ab.clearcode.cc
    {{- else -}}
    external-dns.alpha.kubernetes.io/hostname: {{ $.Values.stackName }}{{ include "model.serviceSuffix" . }}.{{ $.Values.awsRegion }}.ab.clearcode.cc
    {{- end -}}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "model.selectorLabels" $ | nindent 4 }}
{{- end }}
