{
 "title": "Bidder",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bidder_bid_request_received_number[1m]))",
     "legendFormat": "Received bid requests"
    },
    {
     "expr": "sum(irate(bidder_no_bid_number[1m]))",
     "legendFormat": "No bids"
    },
    {
     "expr": "sum(irate(bidder_request_timeout_number[1m]))",
     "legendFormat": "Timeouts"
    },
    {
     "expr": "sum(irate(bidder_server_error_number[1m]))",
     "legendFormat": "Server errors"
    },
    {
     "expr": "sum(irate(bidder_bad_request_number[1m]))",
     "legendFormat": "Bad requests"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (quantile) (bidder_bid_request_time)",
     "legendFormat": "Summary {{quantile}}"
    }
   ]
  },
  {
   "title": "Time range summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(bidder_bid_request_received_number)",
     "legendFormat": "Bid requests"
    },
    { "expr": "sum(bidder_no_bid_number)", "legendFormat": "No bids" },
    {
     "expr": "sum(bidder_request_timeout_number)",
     "legendFormat": "Timeouts"
    },
    {
     "expr": "sum(bidder_server_error_number)",
     "legendFormat": "Server errors"
    },
    { "expr": "sum(bidder_bad_request_number)", "legendFormat": "Bad requests" }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Component throughput per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bidder_device_query_time_count[1m]))",
     "legendFormat": "Device queries"
    },
    {
     "expr": "sum(irate(bidder_kinesis_time_count[1m]))",
     "legendFormat": "Kinesis records (put)"
    }
   ]
  },
  {
   "title": "Component latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (quantile) (bidder_device_query_time)",
     "legendFormat": "Device query ({{quantile}})"
    },
    {
     "expr": "max by (quantile) (bidder_kinesis_time)",
     "legendFormat": "Kinesis requests ({{quantile}})"
    }
   ]
  },
  {
   "title": "Active bid requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bidder_bid_request_active_number)"
    }
   ]
  },
  {
   "title": "Application replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(bidder_bid_request_time_count)"
    }
   ]
  },
  {
   "title": "Cache refresh requests count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bidder_cache_refresh_request_recurring[1m]))",
     "legendFormat": "Cache refresh requests count [recurring]"
    },
    {
     "expr": "sum(irate(bidder_cache_refresh_request_on_demand[1m]))",
     "legendFormat": "Cache refresh requests count [on demand]"
    },
    {
     "expr": "sum(irate(budget_update_time_count[1m]))",
     "legendFormat": "Cache refreshes count"
    }
   ]
  },
  {
   "title": "Budget update latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (quantile) (bidder_budget_update_time)",
     "legendFormat": "Budget update ({{quantile}})"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Queries per table per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table_name, query_type) (irate(bidder_database_time_count[1m]))",
     "legendFormat": "{{table_name}}, {{query_type}}"
    }
   ]
  },
  {
   "title": "Queries per table latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (table_name, query_type) (irate(bidder_database_time[1m]))",
     "legendFormat": "{{table_name}}, {{query_type}}"
    }
   ]
  },
  {
   "title": "Database errors count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(db_device_get_errors_number[1m]))",
     "legendFormat": "DB get device errors count"
    },
    {
     "expr": "sum(irate(db_audience_scan_errors_number[1m]))",
     "legendFormat": "DB get device errors count"
    },
    {
     "expr": "sum(irate(db_budget_scan_errors_number[1m]))",
     "legendFormat": "DB get device errors count"
    },
    {
     "expr": "sum(irate(db_campaign_scan_errors_number[1m]))",
     "legendFormat": "DB get device errors count"
    }
   ]
  },
  {
   "title": "Kinesis producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logical records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(bidder_go_kinesis_producer_user_records_put_total[1m]))",
       "legendFormat": "Count"
      },
      {
       "expr": "sum(irate(bidder_go_kinesis_producer_user_records_data_put_bytes_sum[1m]))",
       "legendFormat": "Total size"
      }
     ]
    },
    {
     "title": "Logical record sizes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(bidder_go_kinesis_producer_user_records_data_put_bytes_bucket[1m])))",
       "legendFormat": "Histogram 0.5"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(bidder_go_kinesis_producer_user_records_data_put_bytes_bucket[1m])))",
       "legendFormat": "Histogram 0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(bidder_go_kinesis_producer_user_records_data_put_bytes_bucket[1m])))",
       "legendFormat": "Histogram 0.99"
      }
     ]
    },
    {
     "title": "Kinesis puts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(bidder_go_kinesis_producer_kinesis_records_put_total[1m]))",
       "legendFormat": "Successful count"
      },
      {
       "expr": "sum(irate(bidder_go_kinesis_producer_kinesis_records_data_put_bytes_sum[1m]))",
       "legendFormat": "Total size"
      },
      {
       "expr": "sum by (code) (irate(bidder_go_kinesis_producer_errors_by_code_total[1m]))",
       "legendFormat": "{{code}} count"
      },
      {
       "expr": "sum(irate(bidder_go_kinesis_producer_retries_per_record_sum[1m]))",
       "legendFormat": "Retry count"
      }
     ]
    },
    {
     "title": "Put record sizes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(bidder_go_kinesis_producer_kinesis_records_data_put_bytes_bucket[1m])))",
       "legendFormat": "Histogram 0.5"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(bidder_go_kinesis_producer_kinesis_records_data_put_bytes_bucket[1m])))",
       "legendFormat": "Histogram 0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(bidder_go_kinesis_producer_kinesis_records_data_put_bytes_bucket[1m])))",
       "legendFormat": "Histogram 0.99"
      }
     ]
    },
    {
     "title": "Kinesis puts per shard",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (shard) (irate(bidder_go_kinesis_producer_kinesis_records_put_total[1m]))",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Records per request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(bidder_go_kinesis_producer_kinesis_records_per_put_records_request_bucket[1m])))",
       "legendFormat": "Histogram 0.5"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(bidder_go_kinesis_producer_kinesis_records_per_put_records_request_bucket[1m])))",
       "legendFormat": "Histogram 0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(bidder_go_kinesis_producer_kinesis_records_per_put_records_request_bucket[1m])))",
       "legendFormat": "Histogram 0.99"
      }
     ]
    },
    {
     "title": "Buffering time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(bidder_go_kinesis_producer_buffering_time_milliseconds_bucket[1m])))",
       "legendFormat": "Histogram 0.9"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(bidder_go_kinesis_producer_buffering_time_milliseconds_bucket[1m])))",
       "legendFormat": "Histogram 0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(bidder_go_kinesis_producer_buffering_time_milliseconds_bucket[1m])))",
       "legendFormat": "Histogram 0.99"
      }
     ]
    },
    {
     "title": "Request time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(bidder_go_kinesis_producer_request_time_milliseconds_bucket[1m])))",
       "legendFormat": "Histogram 0.9"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(bidder_go_kinesis_producer_request_time_milliseconds_bucket[1m])))",
       "legendFormat": "Histogram 0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(bidder_go_kinesis_producer_request_time_milliseconds_bucket[1m])))",
       "legendFormat": "Histogram 0.99"
      }
     ]
    },
    {
     "title": "Kinesis producer buffer sizes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(bidder_go_kinesis_producer_input_buffer_size)",
       "legendFormat": "Input buffer"
      },
      {
       "expr": "max(bidder_go_kinesis_producer_output_buffer_size)",
       "legendFormat": "Output buffer"
      }
     ]
    }
   ]
  }
 ]
}