{
 "title": "AWS Network Load Balancer (NLB)",
 "description": "Visualize AWS Network Load Balancer metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "loadbalancername",
    "label": "LoadBalancerName",
    "query": "dimension_values($region,AWS/NetworkELB, ActiveFlowCount ,LoadBalancer)"
   }
  ]
 },
 "panels": [
  {
   "title": "Net /Active Flow Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ActiveFlowCount",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NewFlowCount",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "New / Active Flow Count TLS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NewFlowCount_TLS",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ActiveFlowCount_TLS",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Healthy / Unhealthy Hosts Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "*" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "ConsumedLCUs / ProcessedBytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ProcessedBytes",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ConsumedLCUs",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "TLSNegotiationErrorCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ClientTLSNegotiationErrorCount",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TargetTLSNegotiationErrorCount",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "TCP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TCP_Client_Reset_Count",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TCP_ELB_Reset_Count",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TCP_Target_Reset_Count",
     "namespace": "AWS/NetworkELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}