{
 "title": "Sockets and TCP Copy",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Sockets used",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pool) (node_sockstat_sockets_used)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "TCP connections in alloc state",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pool) (node_sockstat_TCP_alloc)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "TCP connections in in-use state",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pool) (node_sockstat_TCP_inuse)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "TCP connections in orphan state",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pool) (node_sockstat_TCP_orphan)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "TCP connections in time-wait state",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pool) (node_sockstat_TCP_tw)",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}