apiVersion: batch/v1
kind: Job
metadata:
  name: load-generator
spec:
  ttlSecondsAfterFinished: 10
  parallelism: 60
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      nodeSelector:
        pool: benchmark
      serviceAccountName: load-generator-sa
      restartPolicy: Never
      containers:
        - image: ${AWS_ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/load-generator:latest
          name: load-generator
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 2
          env:
            - name: AWS_REGION
              value: us-east-1
          args:
            - --target=https://us-east-1.ab.clearcode.cc/bidrequest
            - --duration=${duration}
            - --rate=${rate}
            - --workers=16
            - --max-workers=16
            - --profiler-url=http://bidder-internal:8091/debug/pprof/profile
            - --profiler-bucket=aws-bidder-benchmark-files
            - --profiler-output=${profiler_output}
      securityContext:
        fsGroup: 3000 # to be able to read Kubernetes and AWS token files
